# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM)	+= sm6115-fxtec-pro1x.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sm6115p-lenovo-j606f.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sm6125-sony-xperia-seine-pdx201.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sm6125-xiaomi-ginkgo.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sm6125-xiaomi-laurel-sprout.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sm6125-xiaomi-willow.dtb
