# SPDX-License-Identifier: GPL-2.0-only
#
# Rockchip Soc drivers
#
obj-$(CONFIG_ROCKCHIP_GRF) += grf.o
obj-$(CONFIG_ROCKCHIP_IODOMAIN) += io-domain.o
obj-$(CONFIG_ROCKCHIP_DTPM) += dtpm.o
obj-$(CONFIG_ROCKCHIP_MISC_GPIO_A99) += misc-gpio-a99.o
obj-$(CONFIG_ROCKCHIP_MCU_7502) += mcu-7502.o
